spring.application.name=profit-tracker-backend

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true

spring.jpa.open-in-view=false

security.jwt.secret=${JWT_SECRET}
security.jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}

asset.sync.fixed-delay-ms=${ASSET_SYNC_FIXED_DELAY_MS:30000}
asset.sync.initial-delay-ms=${ASSET_SYNC_INITIAL_DELAY_MS:50000}