spring.application.name=profit-tracker-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/profit-tracker-db
spring.datasource.username=user
spring.datasource.password=user
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true